dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./big_integer_testing

after_success:
  - coveralls --root . -E ".*CMakeFiles.*"